language: rust

branches:
  only:
  - master

os:
  - linux

matrix:
  include:
    - rust: nightly
      after_script:
          # Send a notification to the Dusk build Status Telegram channel once the CI build completes
        - bash <(curl -s https://raw.githubusercontent.com/dusk-network/tools/master/bash/telegram_ci_notifications.sh)

before_script:
  - rustup toolchain install beta
  - rustup toolchain install nightly
  - rustup component add rustfmt --toolchain=beta

script:
  - make testfmt CARGO_OPTIONS=+beta
  - make test CARGO_OPTIONS=+nightly
  - make inttest CARGO_OPTIONS=+nightly
